---
 - name: create a directory
   hosts: servers
   become: yes
   become_user: root
   tasks:
      - name: create a directory management
         file:
         path: /home/gkameni/management
         owner: gkameni
         group: gkameni
         mode: 0755
         state: directory
